name: Haskell CI

on:
  push:
    paths:
      - "taffybar.hs"
      - "stack.yaml"
      - "**.cabal"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "taffybar.hs"
      - "stack.yaml"
      - "**.cabal"
      - ".github/workflows/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup GHC with Stack
        uses: haskell/actions/setup@v2
        with:
          ghc-version: "9.0.2"
          enable-stack: true

      - name: Cache ~/.stack
        uses: actions/cache@v3
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-global-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}
          restore-keys: ${{ runner.os }}-stack-global-

      - name: Cache .stack-work
        uses: actions/cache@v3
        with:
          path: .stack-work
          key: ${{ runner.os }}-stack-work-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}-${{ hashFiles('**/*.hs') }}
          restore-keys: ${{ runner.os }}-stack-work-

      - name: Setup hlint
        uses: haskell/actions/hlint-setup@v2

      - name: Run hlint
        uses: haskell/actions/hlint-run@v2
        with:
          path: taffybar.hs
          fail-on: warning

      - name: Install system dependencies
        run: >
          sudo apt-get install libgirepository1.0-dev libwebkit2gtk-4.0-dev libgtksourceview-3.0-dev
          libdbusmenu-gtk3-dev libgirepository1.0-dev

      - name: Install dependencies
        run: |
          stack update
          stack build --only-dependencies

      - name: Build
        run: stack build

      - name: Run tests
        run: stack test
