name: Lint

on:
  push:
    paths:
      - "taffybar.hs"
      - "stack.yaml"
      - "**.cabal"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "taffybar.hs"
      - "stack.yaml"
      - "**.cabal"
      - ".github/workflows/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup hlint
        uses: haskell/actions/hlint-setup@v2

      - name: Run hlint
        uses: haskell/actions/hlint-run@v2
        with:
          path: taffybar.hs
          fail-on: warning
